skating:
  acceleration: 0.1
  max-speed: 2.0
image-fireworks:
  particle-limit: 1024
  list:
    - name: image
      imageName: image.png
      modelData: 20
      displayTime: 1
      flightDuration: 3
